---
name: Push to Galaxy

on:
  push:
    tags:
      - "v*"

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: molecule
        uses: robertdebock/molecule-action@6.0.1

  release:
    needs:
      - test
    runs-on: ubuntu-latest

    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
          git_branch: main
